#!/usr/bin/env bash

[ "$TRACE" == "true" ] && set -x
set -e
set -o pipefail

source /opt/resource/git/common.sh

DEST_DIR="$1"

GIT_DEST_DIR="$(mktemp -d -t git-resource-destination.XXXXXX)"

/opt/resource/git/in "$GIT_DEST_DIR"

PAYLOAD=$(echo /tmp/git-resource-request.*)

load_pubkey $PAYLOAD
configure_git_ssl_verification $PAYLOAD
configure_credentials $PAYLOAD

PROJECT_PATH=$(jq -r '.source["project-path"] // ""' < $PAYLOAD)

cd "$GIT_DEST_DIR/$PROJECT_PATH"

sbt update >&2

mv ~/.ivy2/ "$DEST_DIR/"

echo "Cached $(du -hs "$DEST_DIR/" | cut -f 1) in $(find "$DEST_DIR/" -type f | wc -l) files"
